# Generated by Django 3.2.8 on 2021-10-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
                ('logo', models.ImageField(null=True, upload_to='store/logo/')),
                ('open_time', models.TimeField(null=True)),
                ('close_time', models.TimeField(null=True)),
                ('rating', models.FloatField(default=0, null=True)),
                ('slug', models.SlugField(max_length=64, null=True, unique=True)),
                ('secret_key', models.CharField(max_length=128, null=True, unique=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
                ('store_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storecategory')),
            ],
        ),
    ]
