# Generated by Django 3.2.8 on 2021-10-29 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_email'),
        ('store', '0004_item_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinstore',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.employee'),
        ),
    ]
