# Generated by Django 3.2.8 on 2021-11-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211115_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteamextra',
            options={'verbose_name': 'ItemExtra', 'verbose_name_plural': 'ItemExtra'},
        ),
    ]
