# Generated by Django 3.2.8 on 2021-11-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_iteamextra_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteamextra',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
