# Generated by Django 3.2.8 on 2021-11-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_iteamextra_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteamextra',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/item_extra/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/item/'),
        ),
    ]
