# Generated by Django 3.2.8 on 2021-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211126_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
