# Generated by Django 3.2.8 on 2021-12-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20211127_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.storecategory'),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
