# Generated by Django 3.2.8 on 2021-12-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_store_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, default='store/logo/default-logo.png', null=True, upload_to='store/logo/'),
        ),
    ]
