# Generated by Django 3.2.8 on 2021-11-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[['order failed', 'order failed'], ['order successful', 'order successful'], ['confirm', 'confirm'], ['doing', 'doing'], ['delivery', 'delivery'], ['done', 'done']], default='order successfully', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[['order failed', 'order failed'], ['order successful', 'order successful'], ['confirm', 'confirm'], ['doing', 'doing'], ['delivery', 'delivery'], ['done', 'done']], max_length=32),
        ),
    ]
