# Generated by Django 3.2.8 on 2021-11-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211120_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='location',
            new_name='customer_address',
        ),
    ]
