# Generated by Django 3.2.8 on 2021-11-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customeraddress'),
        ('order', '0005_alter_order_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customeraddress'),
        ),
    ]
