# Generated by Django 3.2.8 on 2021-11-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customeraddress'),
        ('order', '0006_alter_order_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='account.customeraddress'),
            preserve_default=False,
        ),
    ]
