# Generated by Django 3.2.8 on 2021-11-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_iteamextra_name'),
        ('order', '0007_alter_order_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('item_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.iteamextra')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderitem')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
