# Generated by Django 3.2.8 on 2021-11-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='account/avatar/default-avatar.png', null=True, upload_to='account/avatar/'),
        ),
    ]
